- hosts: web_servers
  become: yes
  tasks:
    - name: Verify directory exists
      file: 
        path: "{{ webApp_location }}"
        state: directory

    - name: Copy jar
      copy:
        src: "{{ jar_file }}"
        dest: "{{ webApp_location }}/{{ webApp_name }}"

    - name: Copy Service
      template:
        src: testwebapp.service
        dest: /lib/systemd/system/testwebapp.service 
        mode: 644

    - name: Start Web Service
      systemd: 
        state: restarted
        daemon_reload: yes
        name: testwebapp
